frontend/micro-ui/web/micro-ui-internals/packages/css/package.json

Changed CSS Dependency Issue

---

core-services/egov-searcher/src/main/java/org/egov/search/webservice/SearchSoapService.java
core-services/egov-searcher/src/main/java/org/egov/search/webservice/SearchSoapServiceImpl.java
frontend/micro-ui/web/micro-ui-internals/example/public/index.html
municipal-services/firenoc-services/src/api/create.js
municipal-services/firenoc-services/src/utils/create.js

Anuj firenoc fix

---

municipal-services/sw-calculator/src/main/java/org/egov/swcalculation/service/EstimationService.java

null check for dischargeConnection added

Sewerage issue-demand generation fix

---

municipal-services/tl-calculator/src/main/java/org/egov/tlcalculator/service/CalculationService.java

added null check for validityYears in additionaldetail

TL renewal NPE fix

---

municipal-services/sw-services/src/main/java/org/egov/swservice/service/SewerageServiceImpl.java

sewerage previous conn inactive update for modify connection

sewerage previous conn inactive update for modify connection

---

municipal-services/firenoc-services/src/utils/create.js

API Error Issue

---

municipal-services/sw-services/src/main/java/org/egov/swservice/service/SewerageServiceImpl.java
municipal-services/tl-calculator/src/main/java/org/egov/tlcalculator/service/CalculationService.java
municipal-services/tl-calculator/src/main/java/org/egov/tlcalculator/service/TLRenewalCalculation.java
municipal-services/tl-services/src/main/java/org/egov/tl/util/TradeUtil.java

TL validity years modifications

TL create api validity years

---

municipal-services/firenoc-services/src/utils/create.js

FireNOC fix for forward request

---

municipal-services/property-services/src/main/java/org/egov/pt/validator/PropertyValidator.java

merging from develop hemendiran to pmidc upg dev-3

---

core-services/egov-survey-services/src/main/java/org/egov/egovsurveyservices/service/CategoryService.java
core-services/egov-survey-services/src/main/java/org/egov/egovsurveyservices/service/QuestionService.java
core-services/egov-survey-services/src/main/resources/application.properties
core-services/egov-survey-services/src/test/java/org/egov/egovsurveyservices/service/CategoryServiceTest.java
core-services/egov-survey-services/src/test/java/org/egov/egovsurveyservices/service/QuestionServiceTest.java

added limit 100 in application properties file

added limit to question and category creation

---

core-services/egov-survey-services/pom.xml
core-services/egov-survey-services/src/main/java/org/egov/egovsurveyservices/config/ApplicationProperties.java
core-services/egov-survey-services/src/main/java/org/egov/egovsurveyservices/service/EnrichmentService.java
core-services/egov-survey-services/src/main/java/org/egov/egovsurveyservices/service/ScorecardSurveyService.java
core-services/egov-survey-services/src/main/java/org/egov/egovsurveyservices/utils/ScorecardSurveyUtil.java
core-services/egov-survey-services/src/main/java/org/egov/egovsurveyservices/validators/ScorecardSurveyValidator.java
core-services/egov-survey-services/src/main/java/org/egov/egovsurveyservices/web/controllers/ScorecardSurveyController.java
core-services/egov-survey-services/src/main/java/org/egov/egovsurveyservices/web/models/QuestionWeightage.java
core-services/egov-survey-services/src/main/java/org/egov/egovsurveyservices/web/models/ScorecardSurveyEntity.java
core-services/egov-survey-services/src/main/java/org/egov/egovsurveyservices/web/models/ScorecardSurveyRequest.java
core-services/egov-survey-services/src/main/java/org/egov/egovsurveyservices/web/models/ScorecardSurveyResponse.java
core-services/egov-survey-services/src/main/java/org/egov/egovsurveyservices/web/models/Section.java
core-services/egov-survey-services/src/main/resources/application.properties
core-services/egov-survey-services/src/main/resources/db/migration/main/V20250217000003__survey_db_operations.sql
core-services/egov-survey-services/src/main/resources/db/migration/main/V20250217000003_survey_db_operations.sql

Egov ss survey creation

---

municipal-services/tl-services/src/main/java/org/egov/tl/service/TradeLicenseService.java
municipal-services/tl-services/src/main/java/org/egov/tl/util/TLConstants.java
municipal-services/tl-services/src/main/java/org/egov/tl/web/models/TradeLicense.java
municipal-services/tl-services/src/main/resources/application.properties

tl business service error

---

core-services/egov-survey-services/src/main/java/org/egov/egovsurveyservices/repository/rowmapper/QuestionWeightageWithQuestionRowMapper.java
core-services/egov-survey-services/src/main/java/org/egov/egovsurveyservices/repository/rowmapper/ScorecardSurveyRowMapper.java
core-services/egov-survey-services/src/main/java/org/egov/egovsurveyservices/repository/rowmapper/SectionRowMapper.java
core-services/egov-survey-services/src/main/java/org/egov/egovsurveyservices/service/EnrichmentService.java
core-services/egov-survey-services/src/main/java/org/egov/egovsurveyservices/service/ScorecardSurveyService.java
core-services/egov-survey-services/src/main/java/org/egov/egovsurveyservices/validators/ScorecardSurveyValidator.java
core-services/egov-survey-services/src/main/java/org/egov/egovsurveyservices/web/models/QuestionWeightage.java
core-services/egov-survey-services/src/main/java/org/egov/egovsurveyservices/web/models/Section.java
core-services/egov-survey-services/src/main/resources/db/migration/main/V20250217000003__survey_db_operations.sql
core-services/egov-survey-services/src/test/java/org/egov/egovsurveyservices/repository/rowmapper/ScorecardSurveyRowMapperTest.java
core-services/egov-survey-services/src/test/java/org/egov/egovsurveyservices/service/EnrichmentServiceTest.java
core-services/egov-survey-services/src/test/java/org/egov/egovsurveyservices/service/ScorecardSurveyServiceTest.java
core-services/egov-survey-services/src/test/java/org/egov/egovsurveyservices/validators/ScorecardSurveyValidatorTest.java

In create survey, weightage question/section rounding off to 100 issue solved

Rounding off code updated

---

municipal-services/property-services/src/main/java/org/egov/pt/consumer/FileStoreConsumer.java
municipal-services/property-services/src/main/java/org/egov/pt/repository/PropertyRepository.java
municipal-services/property-services/src/main/java/org/egov/pt/repository/builder/PropertyQueryBuilder.java
municipal-services/property-services/src/main/java/org/egov/pt/service/EnrichmentService.java
municipal-services/property-services/src/main/java/org/egov/pt/service/PropertyService.java
municipal-services/property-services/src/main/java/org/egov/pt/util/PTConstants.java
municipal-services/property-services/src/main/java/org/egov/pt/util/PropertyUtil.java

PI-16853
Improvement Trust to be linked with MC for properties.

PI-16853 Improvement Trust to be linked with MC for properties.

---

core-services/egov-survey-services/src/main/java/org/egov/egovsurveyservices/repository/CategoryRepository.java
core-services/egov-survey-services/src/main/java/org/egov/egovsurveyservices/repository/querybuilder/CategoryQueryBuilder.java

Category title should not be allowing duplicates

Category api title update

---

core-services/egov-survey-services/src/main/java/org/egov/egovsurveyservices/config/ApplicationProperties.java
core-services/egov-survey-services/src/main/java/org/egov/egovsurveyservices/repository/querybuilder/ScorecardSurveyQueryBuilder.java
core-services/egov-survey-services/src/main/resources/application.properties
core-services/egov-survey-services/src/test/java/org/egov/egovsurveyservices/repository/ScorecardSurveyRepositoryTest.java
core-services/egov-survey-services/src/test/java/org/egov/egovsurveyservices/repository/querybuilder/CategoryQueryBuilderTest.java
core-services/egov-survey-services/src/test/java/org/egov/egovsurveyservices/repository/querybuilder/ScorecardSurveyQueryBuilderTest.java
core-services/egov-survey-services/src/test/java/org/egov/egovsurveyservices/service/ScorecardSurveyServiceTest.java
core-services/egov-survey-services/src/test/java/org/egov/egovsurveyservices/validators/ScorecardSurveyValidatorTest.java
core-services/egov-survey-services/src/test/java/org/egov/egovsurveyservices/web/controllers/ScorecardSurveyControllerTest.java

search survey api limit 500 and test cases

search limit 500 and tests

---

frontend/micro-ui/web/micro-ui-internals/packages/libraries/src/hooks/swach/useInboxData.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/swach/src/components/DesktopInbox.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/swach/src/components/SWACHCard.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/swach/src/pages/employee/Inbox.js

Date is Added in Swach Inbox Table and Assigned To All is set by default.

fix: added Date in Swach Inbox

---

core-services/xstate-chatbot/nodejs/src/channel/value-first.js
core-services/xstate-chatbot/nodejs/src/machine/swach.js

Now User will automatically go back to swach menu after Attendance, Raising Observation, Tracking Open Observations. With correct sequence of messages.

Re - Swach Menu

---

frontend/micro-ui/web/docker/Dockerfile
frontend/micro-ui/web/micro-ui-internals/example/devpackage.json
frontend/micro-ui/web/micro-ui-internals/example/package.json
frontend/micro-ui/web/micro-ui-internals/packages/modules/swach/package.json
frontend/micro-ui/web/micro-ui-internals/packages/modules/swach/src/components/inbox/Status.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/swach/src/pages/employee/ComplaintDetails.js
frontend/micro-ui/web/package.json

Fixed - Employee Assign Bug in Swach
Added Status Filters in Swach inbox
Published Swach

Added Status Filter

---

core-services/xstate-chatbot/nodejs/src/machine/service/egov-swach.js

Added Exception Handling in Swach.

fix: Exception Handling in egov-swach

---

core-services/xstate-chatbot/nodejs/src/machine/service/egov-swach.js

Added Exception Handling in swach services

fix: Exception Handling for egov-swach

---

core-services/xstate-chatbot/nodejs/src/machine/swach.js

ASK for City if no city is found after sharing Geo-Location.
Also, select Unknown as Locality if No Locality is found.

fix: Ask City after Geolocation and Select Unknown if No Locality Found

---

core-services/xstate-chatbot/nodejs/src/machine/service/egov-swach.js
core-services/xstate-chatbot/nodejs/src/machine/swach.js

Fixed the Description State in xstate-chatbot

fix: Swach Description

---

frontend/micro-ui/web/micro-ui-internals/packages/css/package.json
frontend/micro-ui/web/micro-ui-internals/packages/css/src/components/card.scss
frontend/micro-ui/web/micro-ui-internals/packages/css/src/pages/citizen/HomePageWrapper.scss
frontend/micro-ui/web/package.json
frontend/micro-ui/web/public/index.html

Swach CSS Made responsive for Citizen Side.

fix: CSS for Swach Citizen and Published Updated CSS

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/templates/ApplicationDetails/Modal/DirectTLModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/templates/ApplicationDetails/Modal/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/templates/ApplicationDetails/config/TLDirectRenewApplication.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/templates/ApplicationDetails/config/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/templates/ApplicationDetails/index.js

Added DirectTL feature in Employee Side

feat: DirectRenew Trade License

---

frontend/micro-ui/web/micro-ui-internals/packages/css/src/components/card.scss
frontend/micro-ui/web/micro-ui-internals/packages/css/src/pages/citizen/container.scss
frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/citizen/Home/LocationSelection.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/swach/src/pages/citizen/ComplaintDetails.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/swach/src/pages/citizen/Create/Steps/SelectGeolocation.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/swach/src/pages/citizen/Create/Steps/SelectImages.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/swach/src/pages/citizen/CreateComplaint/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/swach/src/pages/citizen/Response.js

Add swach citizen side changes, address [object, object] changes, geo-location changes, next common button, remove location test, 
Location dropdown, location & images width changes

Swach citzien side changes

---

frontend/micro-ui/web/docker/Dockerfile
frontend/micro-ui/web/micro-ui-internals/example/devpackage.json
frontend/micro-ui/web/micro-ui-internals/example/package.json
frontend/micro-ui/web/micro-ui-internals/packages/modules/swach/package.json
frontend/micro-ui/web/micro-ui-internals/packages/modules/swach/src/components/DesktopInbox.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/swach/src/components/inbox/Filter.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/swach/src/pages/employee/Inbox.js
frontend/micro-ui/web/package.json

fix pagination, complaint subtype, city changes bugfix

Swach v2 aashish

---

frontend/micro-ui/web/docker/Dockerfile
frontend/micro-ui/web/micro-ui-internals/example/devpackage.json
frontend/micro-ui/web/micro-ui-internals/example/package.json
frontend/micro-ui/web/micro-ui-internals/packages/modules/obps/getAcknowlegment.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/obps/package.json
frontend/micro-ui/web/micro-ui-internals/packages/modules/obps/src/pageComponents/CorrospondenceAddress.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/obps/src/pageComponents/LicenseDetails.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/obps/src/pageComponents/LicenseType.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/obps/src/pageComponents/PermanentAddress.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/obps/src/pages/citizen/StakeholderRegistration/CheckPage.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/obps/src/pages/citizen/StakeholderRegistration/StakeholderAcknowledgement.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/pt/src/Module.js
frontend/micro-ui/web/package.json

Fixed Localization issue of Stakeholder registration in OBPS

Fixed Localization issue of Stakeholder registration in OBPS

---

municipal-services/bpa-services/src/main/java/org/egov/bpa/service/BPAService.java
municipal-services/bpa-services/src/main/java/org/egov/bpa/service/EDCRService.java
municipal-services/bpa-services/src/main/java/org/egov/bpa/util/BPAConstants.java
municipal-services/bpa-services/src/main/java/org/egov/bpa/validator/BPAValidator.java
municipal-services/bpa-services/src/main/java/org/egov/bpa/web/model/landInfo/GeoLocation.java
municipal-services/land-services/src/main/java/org/egov/land/repository/querybuilder/LandQueryBuilder.java
municipal-services/land-services/src/main/java/org/egov/land/repository/rowmapper/LandRowMapper.java

BPA service changes for Stepper form

BPA service changes
